### PR TITLE
mcount_return_trampoline: Don't disable interrupts

### LINKED ISSUE #8: Segmentation fault
When running the rust example on 484a8bda052dff94de1e6f9b88864d261a9618c8, I get `Segmentation fault (core dumped)`.

This is the first commit with this issue.

### PR DESCRIPTION
**Pull request by mkroening**
This fixes #8 for me.

### CODE REVIEW

**Comment by tlambertz** [comment]
Huh yeah, seems I missed that one. Now wondering how it ever worked?
The latest commit was done a few months after my thesis was complete and I was cleaning up my working directory, might have not tested it fully?

If i recall correctly, the reason for the changes in the latest commit were some changes in libhermit which lead to frequent crashes (tracing interrupt-based filesystem writes?). Something with interrupt at inopportune moments, trashing the stack/flags register.

**Comment by mkroening** [comment]
Ah, I see. That makes sense. I have only tested with the rust example, and that one always crashes for me on the latest commit without this fix, as explained in #8.

**Comment by mkroening** [comment]
Ah, nevermind, I did not test this change correctly. I'll rework this.

**Comment by mkroening** [comment]
Ah, sorry. I must have been not very concentrated. Anyway, I found the issue now. The stack has been handled correctly.

The problem is calling `cli` in user space, which is not possible. When you tested this in libhermit you might have tested kernel space only. Removing `cli` makes the example work for me. Why would we need to disable interrupts there in the first place? Any interrupt handler would make sure not to clobber any registers, wouldn't it?

**Comment by tlambertz** [comment]
I think one issue I tried to fix was that an interrupt was arriving while the kernel was in `mcount()`. The interrupt in turn called mcount(), which then overwrote the return pointer of the first mcount() with the trampoline, which broke things.

**Comment by mkroening** [comment]
Ah, so then the problem is the access to `RETSTACK`? I was trying to reproduce the issue to be sure, but I can't get RustyHermit to build with rftrace.

**Pull request closed without merging**
